/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c0cab6',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'surface-variant': '#ceebbd',
        'on-error': '#ffffff',
        'on-background': '#0b2004',
        'on-secondary-fixed': '#052100',
        surface: '#edffdf',
        'tertiary-fixed': '#f5e0bc',
        'on-surface-variant': '#40493b',
        'inverse-primary': '#85db69',
        tertiary: '#605237',
        'tertiary-container': '#7a6a4d',
        'surface-bright': '#edffdf',
        'surface-container-low': '#dffccd',
        'surface-dim': '#c6e3b5',
        'error-container': '#ffdad6',
        'primary-fixed': '#a0f882',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#0b2004',
        'surface-container': '#daf7c8',
        primary: '#156100',
        'on-primary-container': '#c1ffa8',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#d4f1c2',
        'surface-tint': '#196d00',
        'surface-container-highest': '#ceebbd',
        background: '#edffdf',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'secondary-fixed': '#a5f783',
        'on-secondary-container': '#29730c',
        'secondary-container': '#a5f783',
        outline: '#707a69',
        secondary: '#226d03',
        'primary-container': '#2a7c13',
        'inverse-surface': '#203616',
        'secondary-fixed-dim': '#8bda6a',
        'inverse-on-surface': '#dcf9ca',
        'surface-dim': '#c6e3b5',
        'on-primary-fixed': '#032100',
        'on-primary-fixed-variant': '#115300',
        'primary-fixed-dim': '#85db69',
        'on-secondary-fixed': '#052100',
        'on-secondary-fixed-variant': '#165200',
        'on-tertiary-fixed': '#241a05',
        'on-tertiary-fixed-variant': '#52452b',
        'tertiary-fixed-dim': '#d8c4a2',
        'on-tertiary-container': '#ffeccd',
        'on-secondary-container': '#29730c',
        'secondary-container': '#a5f783',
      },
      spacing: {
        'margin-mobile': '1rem',
        'space-xl': '2.5rem',
        'gutter-mobile': '0.75rem',
        gutter: '1.25rem',
        'space-md': '1rem',
        margin: '2rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        xl: '0.75rem',
        lg: '0.5rem',
      },
    },
  },
  plugins: [],
}


